### ISSUE TITLE
Compile error when installing rpforest

### ISSUE THREAD

**Issue by delip** [lyst/rpforest#6]
In file included from rpforest/rpforest_fast.cpp:271:

    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:

    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:

    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:

    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]

    #warning "Using deprecated NumPy API, disable it by " \

     ^

    rpforest/rpforest_fast.cpp:5727:28: error: no member named 'shrink_to_fit' in 'std::vector<int, std::allocator<int> >'

        __pyx_v_node->indices->shrink_to_fit();

        ~~~~~~~~~~~~~~~~~~~~~  ^

    rpforest/rpforest_fast.cpp:5940:28: error: no member named 'shrink_to_fit' in 'std::vector<int, std::allocator<int> >'

        __pyx_v_node->indices->shrink_to_fit();

        ~~~~~~~~~~~~~~~~~~~~~  ^

    1 warning and 2 errors generated.

    error: command 'gcc' failed with exit status 1

**Comment by maciejkula** [comment]
This is because `shrink_to_fit` is a C++ 11 instruction. Can you try compiling it with a compiler that supports C++ 11 while I investigate getting rid of this requirement?

**Comment by delip** [comment]
I am still getting that error after using C++11 options. I'm trying to install via pip on OSX. To enforce C++11 and a C++ compiler, here's what I did:

```
export CC=/usr/bin/clang++
export CFLAGS='-std=c++11'
pip install rpforest
```

Now the generated compile command actually appears to use C++11 options:

```
 /usr/bin/clang++ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c++11 -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/Users/delip/anaconda/include/python2.7 -c rpforest/rpforest_fast.cpp -o build/temp.macosx-10.5-x86_64-2.7/rpforest/rpforest_fast.o
```

But still the compile fails at the same line:

```
 /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    rpforest/rpforest_fast.cpp:5727:28: error: no member named 'shrink_to_fit' in 'std::vector<int, std::allocator<int> >'
        __pyx_v_node->indices->shrink_to_fit();
        ~~~~~~~~~~~~~~~~~~~~~  ^
    rpforest/rpforest_fast.cpp:5940:28: error: no member named 'shrink_to_fit' in 'std::vector<int, std::allocator<int> >'
        __pyx_v_node->indices->shrink_to_fit();
        ~~~~~~~~~~~~~~~~~~~~~  ^
    1 warning and 2 errors generated.
```

    **error: command '/usr/bin/clang++' failed with exit status 1**

**Comment by maciejkula** [comment]
Could you post your version of Clang? I have verified that the package compiles on `Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)`.

I tried to remove the `shrink_to_fit` calls from this branch, maybe you could pull it and try building from it? https://github.com/maciejkula/rpforest/tree/support_old_clang

**Comment by delip** [comment]
```
$ clang++ --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
```

Looks like we are using identical compilers!

**Comment by maciejkula** [comment]
Hmm, I don't really have regular access to a mac so can't dig down further. Have you tried the branch I linked to?

**Comment by delip** [comment]
I was successfully able to install from the branch you made. Thanks! I also confirmed by running test_rpforest.py. There were no assertion failures. 

I notice this branch is behind master by several commits. Can we get this branch in master, if the shrink_to_fit() is not crucial or if there is an alternative for that? I will be happy to test for you.

**Comment by maciejkula** [comment]
Great. I'll do some additional testing and maybe cut a new release in a week or so.

In the meantine I rebased the `support_old_clang` branch on top of master, do you think you can use that until the new release it out?

**Comment by delip** [comment]
Perfect! Thanks!

**Comment by maciejkula** [comment]
Merged into master, will release to pypi soon.

**Comment by delip** [comment]
Thanks!
